import type { Metadata } from "next";
import { Inter } from "next/font/google";
import OverlayStack from "@/components/overlay-stack";

import "../styles/globals.css";
import ReactQueryProvider from "@/lib/react-query-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          {children}
          <OverlayStack />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
